### ISSUE TITLE
Time zone wrong

### ISSUE THREAD

**Issue by han-k59** [rmorgan001/GSServer#2]
Thanks for providing the program.

I have tried 1.0.1.1 and 1.0.1. Both version work. except that my time zone is wrong and I can't set it. My location is about 52 north, 6 degrees east. Timezone it UTC+2.  The time zone should been have set correctly in Windows. There is no option to set  of force the time zone.

Han

update, I'm using Win7 and UTC difference is always 0.00.0000.000

**Comment by rmorgan001** [comment]
The UTC Offset is used by the ascom interface for external applications to adjust the actual UTC time.  It doesn't represent any timezone.  It was added to show any external application connecting to the driver has modified the UTC time being used by the driver.  Is the Local Adjusted Time correct?
