### ISSUE TITLE
Tracking is stopped suddenly

### ISSUE THREAD

**Issue by JuergenTerpe** [rmorgan001/GSServer#20]
**Describe the bug**
The NEQ6 suddenly stops tracking from time to time, during Autofocus or Plate solving or inside an image sequence. 

**To Reproduce**
Happens several times during a night, but is not reproducible directly.  

**Expected behavior**
The tracking should not stop unless tracking is stopped by the user.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - NINA + GS Server
 - NEQ6

In the attached log the error occurs at 23:23, the last successful image was created at 23:19. After that time imaging failed until I checked and tried to bring it back to running around 03:00 - but then I needed to stop imaging due to weather conditions. 
[GSSessionLog2021-12-25-16.txt](https://github.com/rmorgan001/GSServer/files/7777004/GSSessionLog2021-12-25-16.txt)

**Comment by rmorgan001** [comment]
Log shows lot's parse errors from the mount "ErrInvalidData, Response Parse Error: =80vCA2".  The v is an invalid character.  More than likely it's a loose or bad cable. You will need to get this fixed then re-evaluate the issue.  You also ran into the limits at 00:51:00 which was set to turn off tracking.  Go to the website and manual to review the limits settings. https://sites.google.com/view/greenswamp/gsserver/help-videos
