### ISSUE TITLE
Support SynScan Serial over UDP port 11880

### ISSUE THREAD

**Issue by sebgod** [rmorgan001/GSServer#38]
**Is your feature request related to a problem? Please describe.**
I love this driver it seems to be on par with EQMOD and way better than the SynScan App.
One thing the latter does though is able to connect to the SW Wifi dongle

**Describe the solution you'd like**
Support connection to a wifi dongle, which I think uses UDP port 11880 and simply wraps the same protocol as the existing COM part.

**Describe alternatives you've considered**
N/A

**Additional context**
Willing to contribute code if pointed to the right spot.

**Comment by rmorgan001** [comment]
Currently there is no plan to support the SW Wifi dongle.

**Comment by rmorgan001** [comment]
long term  I'll contact them to see if it's possible to support.

**Comment by sebgod** [comment]
Thanks for the info.
I should have provided a bit more context, this is how INDI eqmod does it:
https://github.com/indilib/indi-3rdparty/blob/master/indi-eqmod/eqmodbase.cpp#L298 and here:
https://github.com/indilib/indi-3rdparty/blob/master/indi-eqmod/eqmodbase.cpp#L693

So, from what it seems they essentially just pipe the serial commands over UDP to port 11880. Obviously, discovery would be a bit more evolved.
Just not 100% sure where to look and try this out in your code base I would be willing to contribute this. Your ASCOM driver is lightyears ahead of the SynScan Pro App, which is really not very stable

**Comment by rmorgan001** [comment]
Feel free to email me on the side @ ***@***.***
