### ISSUE TITLE
Moveaxis command not ASCOM compliant?

### ISSUE THREAD

**Issue by han-k59** [rmorgan001/GSServer#40]
I noted the GS server using Moveaxis property behaves different then for example EQMOD and Telescope Simulator.NET. 

The sky moves with 0.004178075 degrees/sec in RA. If I set using ASCOM the property moveaxis(0,0.004178075) then both EQMOD and Telescope Simulator.NET are steady in RA. But via GS Server the mount is moving at double rate sidereal rate. So GS server is adding the value to the sidereal rate and EQMOD and Telescope Simulator.NET are not.

The property is described at:
https://ascom-standards.org/Help/Platform/html/M_ASCOM_DeviceInterface_ITelescopeV3_MoveAxis.htm

There is stated:

> ASCOM_DeviceInterface_ITelescopeV3_AxisRates.htm) are absolute, unsigned values and apply to both directions, determined by the sign used in this command.

Not very clear but it looks like the rate is absolute and not relative to the sidereal rate.  It would be better to adapt GS Sever to this or ask for more clarity from ASCOM developers.

Han

**Comment by han-k59** [comment]
I posted also remark about this at ASCOM developers group to improve the ASCOM specification:

https://ascomtalk.groups.io/g/Developer/message/6213

**Comment by rmorgan001** [comment]
https://github.com/rmorgan001/GSServer/releases/tag/v1.0.5.4b
