### ISSUE TITLE
Ascom command RightAscensionRate result in the wrong RA rate.

### ISSUE THREAD

**Issue by han-k59** [rmorgan001/GSServer#41]
When I set the mount rate in arcsec/sec via method:

https://ascom-standards.org/Help/Platform/html/P_ASCOM_DeviceInterface_ITelescopeV3_RightAscensionRate.htm

Then the mount rate is much too high. I works for the simulator "Telescope simulator.NET"but not for GS Server. Maybe a factor 3600x wrong?

Han

**Comment by rmorgan001** [comment]
Han,

Are you using arcsec/sec to test this?   I think it's seconds per sidereal second. 
The right ascension tracking rate offset from sidereal (seconds per sidereal second, default = 0.0)

**Comment by han-k59** [comment]
Yes it is seconds per sidereal second.

The RA rate of "telescope simulator.NET" has changed a factor 15x since Peter introduced  version ASCOM 6.6sp2 beta. I used to compare with ASCOM simulator 6.6SP1 but that was a mistake.  So likely the fault is not in GS Server. I will check again next days and report back.

https://ascomtalk.groups.io/g/Developer/message/6328

**Comment by rmorgan001** [comment]
ok, just let me know and thanks for all the testing you've done!

**Comment by han-k59** [comment]
Unfortunally RightascensionRate is still too fast. I estimate about 220x too fast.  This could be a factor 15 multiplied instead of divided since 15x15=225.

The DeclinationRate method seems dead. It doesn't move the declination even if I set it at 3600"/hour.

Han

**Comment by rmorgan001** [comment]
https://github.com/rmorgan001/GSServer/releases/tag/v1.0.5.4b
