### ISSUE TITLE
GSS beta SkyTelescopeVM.cs InitializeUdpClients() does not work correctly

### ISSUE THREAD

**Issue by Principia4834** [rmorgan001/GSServer#50]
The LINQ query to populate the networkIfaceIps var has a couple of problems:

- the .Where logic should be || and not && for the NetworkInterfaceTypes. With && no interfaces are returned
- the SortedSet<IPAddress> constructor requires a template argument that supports IComparer - IPAddress does not so an exception is thrown when { ni, ip } pairs are actually returned. The simplest working change is

var networkIfaceIps = NetworkInterface.GetAllNetworkInterfaces()
                    .Where(ni => ni.NetworkInterfaceType == NetworkInterfaceType.Ethernet ||
                                 ni.NetworkInterfaceType == NetworkInterfaceType.GigabitEthernet ||
                                 ni.NetworkInterfaceType == NetworkInterfaceType.Loopback ||
                                 ni.NetworkInterfaceType == NetworkInterfaceType.Wireless80211 ||
                                 ni.OperationalStatus == OperationalStatus.Up && !ni.IsReceiveOnly)
                    .SelectMany(ni => ni.GetIPProperties().UnicastAddresses, (ni, ip) => new { ni, ip })
                    .Where(@t => @t.ip.Address.AddressFamily == AddressFamily.InterNetwork)
                    .Select(@t => @t.ip.Address);

It is easy to extend the IPAddress type with a custom comparer (see stack hub and others) but probably not needed.

Andy

**Comment by rmorgan001** [comment]
should be okay now, thanks

**Comment by rmorgan001** [comment]
closing
