### ISSUE TITLE
RA coordinates format

### ISSUE THREAD

**Issue by rmorgan001** [rmorgan001/GSServer#67]
Allow RA coordinates on the main tab to read as Degree, Minutes and Seconds or Hours, Minutes and Seconds.  Maybe do a right click to switch between each.

**Comment by Principia4834** [comment]
I support providing the option. At the moment I do the x15 conversion mentally when I want to relate RA motion to actual mount angle so that would be easier. May also be helpful when checking pulse guiding or slewing manually.

**Comment by rmorgan001** [comment]
will be in 1.0.8.6 release
