### ISSUE TITLE
Get RA/DEC from Planetarium

### ISSUE THREAD

**Issue by danielastro** [rmorgan001/GSServer#78]
When doing deep sky, i have no problem doing a platesolve and sync (all done from NINA) and it works great. When I do planetary. it is almost impossible to do a platesolve due to the lack of stars on my capture. What I do is go to Stellarium, the planetarium i use, select the planet I have centered in the camera, copy manually the RA/DEC, and insert them in the main window of GSServer and do a Sync. This improves my tracking greatly since once I sync the coordinates, the planet remains perfectly centered.
The feature I would like to see is the ability to import the coordinates of the selected planetarium object in the main window and then sync. 
in NINA, I can use this feature to get coordinates from the planetarium in the framing assistant. It uses the Remote control Plugin in Stellarium. It gets the name of the object and its RA/DEC.

Thank you

NINA and Stellarium Screenshots:
![Screenshot (327)](https://github.com/user-attachments/assets/6268c3e7-5549-4fd2-bcc1-f4918cd0addd)
![Screenshot (326)](https://github.com/user-attachments/assets/25bf4df9-3550-40fd-9261-bcdbb847966e)
![Screenshot (325)](https://github.com/user-attachments/assets/57ac872f-8c45-4667-bc30-d4560d6780b9)
![Screenshot (322)](https://github.com/user-attachments/assets/a789ce8b-f6f2-4dba-a5ad-e09c2cc91a64)
![Screenshot (320)](https://github.com/user-attachments/assets/a5f55e97-7bc2-4c40-8eea-7a467cbb8690)

**Comment by danielastro** [comment]
Should works for me. Will try that and let you know.

Thanks

Daniel

On Oct 1, 2024, at 10:14, AndyW ***@***.***> wrote:

﻿

As I read it your requirement it is to get GSS to sync with the position of a planet that you have centred in the camera. Your suggestion is to get GSS to retrieve the planet's RA / Dec from Stellarium and then use the "Sync" button on GSS| to set the mount's Ra / Dec axes to the actual pointing position.

Stellarium's "Current Object" dialogue screen has a "Sync" button which may do what you require if you follow these steps:

  *   Press ctrl-0 to bring up the "Slew telescope to" dialog (that's numeric zero not letter O)
  *   Use the "Configure Telescopes ..." button to connect to the GSS telescope using ASCOM - you should see the telescope position appear as a cross-hair cursor
  *   Select the planet and make it the Current Object and press "Slew". The telescope mount should move to where it thinks the planet is and start tracking
  *   Centre the planet in the camera fov using the GSS arrow keys or a gamepad controller if you have one. The telescope cross hairs in Stellarium will no longer be centred on the planet
  *   Press the "Sync" button on the Stellarium "Slew telescope to" dialog. This will tell GSS to take the planet's RA / Dec sync the mount axes to these values. The telescope cross hairs in Stellarium will jump to be centred on the planet but the mount will not have moved

Tracking should now keep the planet centred. Let me know if this works for you or I haven't correctly understood your requirement.

Andy

**Comment by danielastro** [comment]
Andy,

Tested it again tonight and the workaround is perfect.

Just one piece of additional information, I have been experiencing random crash of Stellarium for a few month. While testing the workaround tonight, it happened again a few times, so I dug a bit deeper to find out that the QT6 versions of Stellarium have been problematic with ASCOM drivers and they recommend using the QT5 version of Stellarium until they find a fix.
Problem solved...

Productive evening...

Thanks
Daniel

**Comment by Principia4834** [comment]
Daniel
Thanks for the feedback - pleased that it works. I too have found problems with Stellarium QT6 and I am running the QT5 build. version 24.2. I'll log a problem with the Stellarium developers although I don't expect a solution - there have been long running issues with QT6 and I'm not sure if it is QT6 bug or a Stellarium problem.
Andy
